### ISSUE TITLE
WebGL support?

### ISSUE THREAD

**Issue by maxplayrix** [netpyoung/unity.webp#10]
Hi! I was trying to use your lib in WebGL project, but I've got an error:
`uncaught exception: abort("To use dlopen, you need to use Emscripten's linking support, see https://github.com/kripken/emscripten/wiki/Linking") at jsStackTrace`

So, how difficult to make this lib works on WebGL platform? I can try to do it myself but I need some help with this. Can you give me some advice on how I can do it. Or the best way if you can do lib with WebGL support. Thank you.

**Comment by netpyoung** [comment]
Hi @maxplayrix .
Currently this project doesn't support WebGL.(only iOS, Android, Windows, Linux )
I didn't image to support that.

From your Issue, I'm interesting to support WebGL. I will try to find a way to support WebGL in this library.
But I don't have experience to making library for WebGL.  So It take a time or long time.

If you found some useful link to making library for WebGL. Please comment to this issue.
 
or I will be happy, If you are fork this repo and contribute.

**Comment by netpyoung** [comment]
* https://blogs.unity3d.com/2017/01/19/low-level-plugins-in-unity-webgl/
* https://docs.unity3d.com/Manual/webgl-interactingwithbrowserscripting.html

**Comment by netpyoung** [comment]
https://developer.mozilla.org/en-US/docs/WebAssembly/existing_C_to_wasm

**Comment by maxplayrix** [comment]
Hi! Thank you for the answer. I also tried to investigate this topic and found the same links as you. And me too don't have this kind of experience, but I will try to do to something in the future. Cause anyway it will be needed in the project I'm working on.

**Comment by netpyoung** [comment]
https://webmproject.github.io/libwebp-demo/webp_wasm/index.html

C# - js - wasm

**Comment by suntabu** [comment]
Hello,
Do you have any progress on this issue?

**Comment by isurfraz** [comment]
Was any progress made on this?

**Comment by netpyoung** [comment]
with b0ece32190734abe4660465eb66fb4355e72b8fa , f749713de0ae56065037c85728de5ffff7949aa4, Now It can be built for WebGL
