### ISSUE TITLE
Help building libwebpdemux.so

### ISSUE THREAD

**Issue by sharedNoob** [netpyoung/unity.webp#11]
Hi, your project is great!
I started to write a wrapper for the animation (demux) but it's been more than a week that I'm trying to build the demux shared library for Android and Ios (libwebpdemux.so), Can you please explain me how to do that ?

**Comment by netpyoung** [comment]
@sharedNoob sorrty late reply. in my memory libwebp contains webpdemux. but i'm not sure I will check it later when I have a time.

**Comment by netpyoung** [comment]
https://github.com/netpyoung/unity.webp/pull/17
