### ISSUE TITLE
Support Android 64 bit

### ISSUE THREAD

**Issue by DevAhnsh** [netpyoung/unity.webp#16]
Hi.
Thanks for making the good library.

Can you make the android file 'libwebp.so' as 64bit version?

**Comment by netpyoung** [comment]
Actually I prebuild for 64bit for android on [libwebpdemux branch](https://github.com/netpyoung/unity.webp/tree/libwebpdemux)

Could check this?

- https://github.com/netpyoung/unity.webp/tree/libwebpdemux/unity_project/Assets/unity.webp/Plugins/Android/libs/arm64-v8a

**Comment by DevAhnsh** [comment]
Thank you.
I applied that branch to my project successfully. :)
