### ISSUE TITLE
macOs: Plugins: Couldn't open Assets/unity.webp/Plugins/x64/webpdemux.bundle, error: 

### ISSUE THREAD

**Issue by netpyoung** [netpyoung/unity.webp#19]
From #18 

```
Plugins: Couldn't open Assets/unity.webp/Plugins/x64/webpdemux.bundle, error: 
dlopen(Assets/unity.webp/Plugins/x64/webpdemux.bundle, 2): 
Library not loaded: /Users/pyoung/deleteme/unity.webp/libwebp/.lib/lib/libwebp.7.dylib
  Referenced from: /Users/huangqingfeng/Documents/code/skillz/unity/Assets/unity.webp/Plugins/x64/webpdemux.bundle
  Reason: image not found

```

It seems my personal path embedded in webpdemux.bundle.

- try using `install_name_tool` to change my path to relative path.
- Because I don't have mac machine now, So, who using this library please manually build using my buildscript until this issue fix.
  - https://github.com/netpyoung/unity.webp/blob/master/Rakefile#L18

**Comment by shunia** [comment]
Self compiled library result:

WebP files without animation: WRONG, error shows:
```
Exception: Invalid WebP header detected
WebP.Texture2DExt.GetWebPDimensions (System.Byte[] lData, System.Int32& lWidth, System.Int32& lHeight) (at Assets/Plugins/unity.webp/Texture2DExt.cs:87)
WebP.Texture2DExt.CreateTexture2DFromWebP (System.Byte[] lData, System.Boolean lMipmaps, System.Boolean lLinear, WebP.Error& lError, WebP.Texture2DExt+ScalingFunction scalingFunction) (at Assets/Plugins/unity.webp/Texture2DExt.cs:211)
```

WebP files with animation: CORRECT

**Comment by netpyoung** [comment]
Um.. that also seems like path problem.. on on mac.
Is it working well sample image on example directory?

**Comment by netpyoung** [comment]
fixed by https://github.com/netpyoung/unity.webp/commit/5c7b287dbf899173eb07a18c715bf5559f910a8e
