### ISSUE TITLE
How to control animations

### ISSUE THREAD

**Issue by dburongarcia** [netpyoung/unity.webp#23]
Hello, I was wondering if there is any way to control animations easily. I'm checking example2 but I'm not sure if there is an easy way to access the texture list and pause, play, rewind or even apply tweens using something like DOTween. Thanks.

**Comment by netpyoung** [comment]
Hi. I provided example function
- https://github.com/netpyoung/unity.webp/blob/master/unity_project/Assets/example2/WebpAnimation.cs#L40

that function return List of (texture, timestamp).
So You can combine your tween or logic with that function

**Comment by netpyoung** [comment]
please reopen this issue If you doesn't find a way to do
