### ISSUE TITLE
unity.webp - WebGL

### ISSUE THREAD

**Issue by Hela-Girl** [netpyoung/unity.webp#35]
Hello, there are a lot of errors for WebGL please fix it, support for Unity (webp - WebGL) is really needed.

Assets\unity.webp\Runtime\NativeWrapper\Demux\Demux.cs(31,20): error CS0103: The name 'DLL_NAME' does not exist in the current context

**Comment by netpyoung** [comment]
Well, current unity.webp does not support WebGL platform.

- duplicate issue #10
