### ISSUE TITLE
WebP source code

### ISSUE THREAD

**Issue by NikMikk** [netpyoung/unity.webp#38]
Hi!

First of all, this library works wonders, I'm using this library in our game and it works wonders on Windows.

My current issue is that I need to compile a native .dll file for Nintendo Switch so I need access to the WebP source code, I need to run it through their compiler. How can I compile the project? :)

**Comment by netpyoung** [comment]
Hey!

Webp is google's opensource, so you can freely access source code https://github.com/webmproject/libwebp .

``` sh
## example - idk it's work or not.
./autogen.sh
./configure --prefix=`pwd`/.lib --enable-everything --disable-static
make && make install
```

**Comment by NikMikk** [comment]
Thanks for that, can't get it to compile, I guess that's something for me to look into ^^
