### ISSUE TITLE
ios don't work

### ISSUE THREAD

**Issue by kiu123123123** [netpyoung/unity.webp#4]
DllNotFoundException: Unable to load DLL 'webp': The specified module could not be found.
  at WebP.Extern.NativeBindings.WebPGetInfo (System.IntPtr data, System.UIntPtr data_size,

**Comment by netpyoung** [comment]
Could I get information about that? Unity version, xcode version etc...

**Comment by bigstupidx** [comment]
Sorry, holidays.

Unity4.7.2f1
Xcode Version 9.2 (9C40b)
macOS Sierra(10.12.6)

The webp.bundle is not working in unity4.x, but worked good in unity5+, I think it's 32bit related, the Unity4.x is 32bit and unity5+ is 64bit.

**Comment by netpyoung** [comment]
@kiu123123123 maybe It cause by #6 
Let's try agin.

**Comment by kiu123123123** [comment]
problem solve
