### ISSUE TITLE
help me, please

### ISSUE THREAD

**Issue by bigstupidx** [netpyoung/unity.webp#5]
I don't know how to create webp.bundle for unityosx from the webp source code on mac, could you teach me the steps?

**Comment by netpyoung** [comment]
step describes on https://developers.google.com/speed/webp/docs/compiling

and I using script for build
https://github.com/netpyoung/unity.webp/blob/a89be75012d3fdff78288a89df2085598492266f/Rakefile#L14

1. download source
2. ./configure && make && make install
3. osx - https://github.com/netpyoung/unity.webp/blob/a89be75012d3fdff78288a89df2085598492266f/Rakefile#L31
4. ios - https://github.com/netpyoung/unity.webp/blob/a89be75012d3fdff78288a89df2085598492266f/Rakefile#L62

**Comment by bigstupidx** [comment]
Thank you so much, I will try it myself.

**Comment by bigstupidx** [comment]
when I run command:
`rake update_library_osx `

I got the following error:
_rake aborted!
No such file or directory - realpath
/Users/king/e/tools/webp/unity.webp/Rakefile:31:in ``'
/Users/king/e/tools/webp/unity.webp/Rakefile:31:in `block (2 levels) in <top (required)>'
/Users/king/e/tools/webp/unity.webp/Rakefile:30:in `chdir'
/Users/king/e/tools/webp/unity.webp/Rakefile:30:in `block in <top (required)>'
Tasks: TOP => update_library_osx
(See full trace by running task with --trace)_

I already run command `rake install_webp`
also I check the files in the folder "libwebp/src/.libs", the files are as following:
libwebp.7.dylib libwebp.a       libwebp.dylib   libwebp.la      libwebp.lai

**Comment by netpyoung** [comment]
maybe you are missing `realpath` command.

```
[~/temp/unity.webp]$ rake update_library_osx                                                                [master]
cp -r /Users/pyoung/temp/unity.webp/libwebp-0.6.0/src/.libs/libwebp.7.dylib /Users/pyoung/temp/unity.webp/unity_project/Assets/unity.webp/Plugins/x64/webp.bundle
```

`unity.webp/libwebp-0.6.0/src/.libs/libwebp.7.dylib`  is `webp.bundle` what i using for osx.

**Comment by bigstupidx** [comment]
Yeap, finally I build it out on my mac!!!
but one more question occurs.
the webp.bundle worked good in unity5+, but does not work in unity4.x  It seems the unity4 is 32bit while unity5+ is 64bit, so it errored as "dll not found"

Could you teach me how to build a 32bit bundle?

**Comment by netpyoung** [comment]
actually I don't have a plan to support 32bit on osx.
anyway you can compile 32bit bundle using compile option
`./configure` use default 64bit settings so you need to change below

`CFLAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32 ./configure`

**Comment by netpyoung** [comment]
@bigstupidx Do you solve your problem? Could I close this issue??

**Comment by bigstupidx** [comment]
I upgraded the unity version to unity5+ to solve this problem

but on unity4.x, it still not work on mac

after I run the following commands
`CFLAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32 ./configure`
`make`

It error as:

`Making all in utils
  CC       bit_reader_utils.lo
  CC       color_cache_utils.lo
  CC       filters_utils.lo
  CC       huffman_utils.lo
  CC       quant_levels_dec_utils.lo
  CC       rescaler_utils.lo
  CC       thread_utils.lo
  CC       utils.lo
  CC       bit_writer_utils.lo
  CC       huffman_encode_utils.lo
  CCLD     libwebputils.la
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: .libs/libwebputils.a(random_utils.o) cputype (16777223) does not match previous archive members cputype (7) (all members must match)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: .libs/libwebputils.a(quant_levels_utils.o) cputype (16777223) does not match previous archive members cputype (7) (all members must match)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: .libs/libwebputils.a(random_utils.o) cputype (16777223) does not match previous archive members cputype (7) (all members must match)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: .libs/libwebputils.a(quant_levels_utils.o) cputype (16777223) does not match previous archive members cputype (7) (all members must match)
make[2]: *** [libwebputils.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
`

osx 10.12.6, xcode 9.2(9C40b)

**Comment by netpyoung** [comment]
@bigstupidx I will close this issue, but If any problem about that, please reopen that issue. Thank you.
