### ISSUE TITLE
Help me, the example does not build ios

### ISSUE THREAD

**Issue by kwangrim** [netpyoung/unity.webp#6]
Can you upload a working example?

please...TT

**Comment by netpyoung** [comment]
I already tested this library on my device few month ago.
Could I receive more information about build environment?
Unity version and Xcode version and ios version.... etc...

Anyway I'm not sure I have a time to testing that....

**Comment by kwangrim** [comment]
Thank you comments

A build error occurs at the part of NativeBindings.cs.

#if UNITY_EDITOR
	const string DLL_NAME = "webp";		
#elif UNITY_ANDROID
	const string DLL_NAME = "webp";		
#elif UNITY_IOS
	const string DLL_NAME = DLL_NAME;		
#endif

Replacing DLL_NAME with "webp" will build but not image.

I would appreciate if you could share a unity project that works properly on iOS.

My system information is as follows.
unity: 5.6.4p4
macOS: 10.13.2
xcode: 9.3

**Comment by netpyoung** [comment]
That's a bug for me. 

For ios, we need to change DLL_NAME to "__Internal"

```cs
#if UNITY_EDITOR
const string DLL_NAME = "webp";
#elif UNITY_ANDROID
const string DLL_NAME = "webp";
#elif UNITY_IOS
const string DLL_NAME = "__Internal";
#endif
```

**Comment by kwangrim** [comment]
It works well.
thank you.

**Comment by netpyoung** [comment]
it was fixed.
