### ISSUE TITLE
how about the (Texture atlas)

### ISSUE THREAD

**Issue by Turkm** [netpyoung/unity.webp#9]
hi, (again)
since we cant see the image in editing time and just see it at the runtime  so i figured out that we cant use Texture atlas and we cant use these images for 2D skeletal animation like  Spine2d or Spriter2D, am i right or there is a turn around?

**Comment by netpyoung** [comment]
simply yes. it is hard to see on edit mode.

on SpriteAtlas you can not access api.
but spine2d, you can access code and you can modify viewing even editor mode.

**Comment by Turkm** [comment]
actually im using Puppet2D which is an asset written in C# for unity, and of course i hae the source so i can access it's api, thanks for the answer. 🥇
